### ISSUE TITLE
linear Gauge not work on IE11

### ISSUE THREAD

**Issue by ybenameur** [Mikhus/canvas-gauges#101]
Hi
Version 2.1.1
i tested the 2 examples shipped with the download .i tried them on Firefox all is ok but on IE they dont work at all ( black screen with 2 buttons : animate & stop animation).
1.linear-component.html
2.linear-min-non-zero.html
in edge they work as well.
in the html code i added the meta tag
	meta http-equiv="X-UA-Compatible" content="IE=edge"  (with brackets)
but not sucessfull.
Another question : how can make lineargradient or a clipped image as gauge  background ?
thank you.

**Comment by Mikhus** [comment]
Fixed in branch 2.1.2
