### ISSUE TITLE
data-value attribute issue on LCD RPi

### ISSUE THREAD

**Issue by iltafhussain352** [Mikhus/canvas-gauges#110]
dear brother 
I have used your library and gauge meters in my project.
I fetch real time data from generator and show on meter.
For this purpose I use ajax to fetch data continuously. The 
needle of meter works fine on my laptop screen but I use this
meter on lcd of Raspberry pi which is small in size. The needle
of the meter does not respond the data. Please suggest the solution.

**Comment by PetroGolovnya** [comment]
show your code on [https://jsfiddle.net/](url)

**Comment by iltafhussain352** [comment]
i use the following code . i m accessing the canvas by id and changing the data-value attribute by ajax;

<canvas
                       id="canvas6" 
                       data-type="radial-gauge"
                       data-width="150"
                       data-height="150"
                       data-units="BATTERY VOLTS"
                       data-title="VDC"
                       data-min-value="0"
                       data-max-value="30"
                       data-value="42.3"
                       data-animate-on-init="true"
                       data-major-ticks="0,5,10,15,20,25,30"
                       data-minor-ticks="2"
                       data-stroke-ticks="true"
                       data-highlights='[{"from": 20, "to": 30, "color": "rgba(200, 50, 50, .75)"}]'
                       data-color-plate="#222"
                       data-color-major-ticks="#f5f5f5"
                       data-color-minor-ticks="#ddd"
                       data-color-title="#fff"
                       data-color-units="#ccc"
                       data-color-numbers="#eee"
                       data-color-needle-start="rgba(240, 128, 128, 1)"
                       data-color-needle-end="rgba(255, 160, 122, .9)"
                       data-value-box="true"
                       data-font-value="Led"
                       data-font-numbers="10"
                       data-animated-value="true"
                       data-borders="false"
                       data-border-shadow-width="0"
                       data-needle-type="arrow"
                       data-needle-width="2"
                       data-needle-circle-size="7"
                       data-needle-circle-outer="true"
                       data-needle-circle-inner="false"
                       data-animation-duration="1500"
                       data-animation-rule="linear"
                       data-ticks-angle="250"
                       data-start-angle="55"
                       data-color-needle-shadow-down="#333"
                       data-value-box-width="45"
                    ></canvas>
var canvas6 = document.getElementById("canvas6");
canvas6.setAttribute("data-value",200);

**Comment by iltafhussain352** [comment]
i use the following code. im accessing the canvas by id.. and changing data-value attribute by Ajax.


<canvas
                       id="canvas6" 
                       data-type="radial-gauge"
                       data-width="150"
                       data-height="150"
                       data-units="BATTERY VOLTS"
                       data-title="VDC"
                       data-min-value="0"
                       data-max-value="30"
                       data-value="42.3"
                       data-animate-on-init="true"
                       data-major-ticks="0,5,10,15,20,25,30"
                       data-minor-ticks="2"
                       data-stroke-ticks="true"
                       data-highlights='[{"from": 20, "to": 30, "color": "rgba(200, 50, 50, .75)"}]'
                       data-color-plate="#222"
                       data-color-major-ticks="#f5f5f5"
                       data-color-minor-ticks="#ddd"
                       data-color-title="#fff"
                       data-color-units="#ccc"
                       data-color-numbers="#eee"
                       data-color-needle-start="rgba(240, 128, 128, 1)"
                       data-color-needle-end="rgba(255, 160, 122, .9)"
                       data-value-box="true"
                       data-font-value="Led"
                       data-font-numbers="10"
                       data-animated-value="true"
                       data-borders="false"
                       data-border-shadow-width="0"
                       data-needle-type="arrow"
                       data-needle-width="2"
                       data-needle-circle-size="7"
                       data-needle-circle-outer="true"
                       data-needle-circle-inner="false"
                       data-animation-duration="1500"
                       data-animation-rule="linear"
                       data-ticks-angle="250"
                       data-start-angle="55"
                       data-color-needle-shadow-down="#333"
                       data-value-box-width="45"
                    ></canvas>
var canvas6 = document.getElementById("canvas6");
canvas6.setAttribute("data-value",200);

**Comment by PetroGolovnya** [comment]
show me values of "canvas6" attributes.  data-min-value, data-max-value, data-major-ticks

**Comment by iltafhussain352** [comment]
<div class="col-lg-23 col-md-6">
                        	 <canvas
                        id="canvas6" 
                        data-type="radial-gauge"
                        data-width="150"
                        data-height="150"
                        data-units="VDC"
                        data-title="BATTERY VOLTS"
                        data-min-value="0"
                        data-max-value="30"
                        data-value="0"
                        data-animate-on-init="true"
                        data-major-ticks="0,5,10,15,20,25,30"
                        data-minor-ticks="2"
                        data-stroke-ticks="true"
                        data-highlights='[{"from": 20, "to": 30, "color": "rgba(200, 50, 50, .75)"}]'
                        data-color-plate="#222"
                        data-color-major-ticks="#f5f5f5"
                        data-color-minor-ticks="#ddd"
                        data-color-title="#fff"
                        data-color-units="#ccc"
                        data-color-numbers="#eee"
                        data-color-needle-start="rgba(240, 128, 128, 1)"
                        data-color-needle-end="rgba(255, 160, 122, .9)"
                        data-value-box="true"
                        data-font-value="Led"
                        data-font-numbers="10"
                        data-animated-value="true"
                        data-borders="false"
                        data-border-shadow-width="0"
                        data-needle-type="arrow"
                        data-needle-width="2"
                        data-needle-circle-size="7"
                        data-needle-circle-outer="true"
                        data-needle-circle-inner="false"
                        data-animation-duration="1500"
                        data-animation-rule="linear"
                        data-ticks-angle="250"
                        data-start-angle="55"
                        data-color-needle-shadow-down="#333"
                        data-value-box-width="45"
                     ></canvas>  
                        </div>
this is one of the canvas i use in my proj,
thanks in advance for any kind of help
