### ISSUE TITLE
Download guide shows incomplete URL in Script for CDN.rawgit.com, missing scheme:

### ISSUE THREAD

**Issue by sgornick** [Mikhus/canvas-gauges#111]
The issue can be seen on the Download guide at the [Loading From CDN](https://canvas-gauges.com/download/#loading-from-cdn) section.

The URL should have https:  scheme prefixing the path ( e.g.,src="https://cdn.rawgit.com/..." ), otherwise the browser tries to load locally ( i.e., file://cdn.rawgit.com/... ) and reports this error:

    GET file://cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/2.1.2/all/gauge.min.js net::ERR_FILE_NOT_FOUND

Here's the section of the guide:

**Loading From CDN**

*All-in-one*

    <script src="//cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/2.1.2/all/gauge.min.js"></script>

Should include the scheme for the URI: (i.e. https: ):

    <script src="https://cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/2.1.2/all/gauge.min.js"></script>

This problem exists for all three Scripts: "All-in-one", "Only radial gauge", and "Only linear gauge".

**Comment by Mikhus** [comment]
It does not missing. Omitting the scheme guarantees it will use current document scheme.
