### ISSUE TITLE
Logarithmic scales - possible ??

### ISSUE THREAD

**Issue by softfoot** [Mikhus/canvas-gauges#113]
Is there a way to set the ticks to emulate a logarithmic scale.

I'm looking for a way to display low values clearly but still have a very high maximum.

For example a maximum of say 100,000 but be able to display 100, 200 etc.

The major ticks would need to be at 100, 1000, 10000, 100000 with minor ticks at
200, 400, 800, 2000, 4000, 8000, 20000, 40000, ... etc

The tick marks should be equally spaced between min and max.

Best regards.

**Comment by Mikhus** [comment]
Major ticks by default are a lables. So you can specify "100k", "200k" for example, but minValue and maxValue set to an actual numbers like 100000, 200000. Is it something you are looking for or I misunderstand something?

**Comment by softfoot** [comment]
On 06/03/2017 16:21, Mykhailo Stadnyk wrote:
>
> Major ticks by default are a lables. So you can specify "100k", "200k" 
> for example, but minValue and maxValue set to an actual numbers like 
> 100000, 200000. Is it something you are looking for or I misunderstand 
> something?
>

I'll have a play and see if I can achieve what I need ... thanks for the 
info.
Dave

**Comment by softfoot** [comment]
> Major ticks by default are a lables. So you can specify "100k", "200k" 
> for example, but minValue and maxValue set to an actual numbers like 
> 100000, 200000. Is it something you are looking for or I misunderstand 
> something?
>

Hmmm ... nearly there ... Is it possible to display a different value in 
the "value" box to that pointed to by the needle ??

Regards, Dave

**Comment by Mikhus** [comment]
You can display arbitrary text or exact value there and customize number format. That is all. Or you may draw your custom value box using rendering events, if the implemented one is not satisfying your needs.

**Comment by softfoot** [comment]
On 08/03/2017 10:47, Mykhailo Stadnyk wrote:

You can display arbitrary text or exact value there and customize number format. That is all. Or you may draw your custom value box using rendering events, if the implemented one is not satisfying your needs.

**Comment by softfoot** [comment]
>> You can display arbitrary text or exact value there and customize 
number format. That is all.
 >> Or you may draw your custom value box using rendering events, if the 
implemented one is not satisfying your needs.

Sorry for multiple messages - there is something odd going on with this 
email client :-(

Is there an example of sending "arbitrary text" to a value box ??

JS is not my language of choice and a clue or hint would be most welcome.

Best regards,
Dave

**Comment by Mikhus** [comment]
https://rawgit.com/Mikhus/canvas-gauges/master/examples/radial-component.html

Just press "Set value text" button at the top of the page. Sources are available bot in view sourcein the browser or here on github in examples folder.

**Comment by softfoot** [comment]
>>> https://rawgit.com/Mikhus/canvas-gauges/master/examples/radial-component.html<https://rawgit.com/Mikhus/canvas-gauges/master/examples/radial-component.html>

>>> Just press "Set value text" button at the top of the page. Sources are available bot in view sourcein the
>>> browser or here on github in examples folder.

Thanks for that ... I am trying the following ...

                <td style="text-align:center"><canvas id="an_gauge_33"
                    data-major-ticks="100 1K 10K 100K 1000K"
                    data-minor-ticks="1"
                    data-type="canv-gauge"
                    data-title="Solar Power"
                    data-units="Lux"
                    data-value-format="0.2"
                    data-min-value="2"
                    data-max-value="6"
                    data-glow="true"
                    data-highlights="2 3 #F00, 3 5 #00F, 5 6 #0F0"
                    data-onready="setInterval( function() { Gauge.Collection.get('an_gauge_33').setValue(solarfluxos);
                                                            Gauge.Collection.get('an_gauge_33').update({ valueText: text }); }, 5000);"></canvas></td>

Where "solarfluxos"=3.95 and "text" is a simple string "1234"

But I am seeing an error on the console "TypeError: Gauge.Collection.get(...).update is not a function".

I realize that my html is a different format from your example so my expectation of what "Gauge.Collection.get('an_gauge_33')"
returns may be wrong - can you point me in the correct direction, please?

Thanks for your help,
Dave

**Comment by softfoot** [comment]
OK Never mind ... I seem to have been using a rather old version of your 
package.

I'll update then try again.

Many thanks for your help.
Dave

**Comment by softfoot** [comment]
OK -- upgrading to latest version solved all my problems
Many thanks,
Dave

**Comment by Mikhus** [comment]
You are welcome!
