### ISSUE TITLE
Change value box location help needed

### ISSUE THREAD

**Issue by gjt211** [Mikhus/canvas-gauges#116]
I have three radial gauges on my page and they are all working well, however I am trying to move the value box on one specific gauge and can't work out how to do that.
Is there an option that I can use to change the value box position on the gauge?

**Comment by Mikhus** [comment]
Nope, you can't do that with any option. The only way for the moment is to draw your own custom value box. To do that you have to inject into drawing process using appropriate events. Read some info here: https://canvas-gauges.com/documentation/user-guide/scripting-api#injecting-into-gauge-drawing-workflow 

And take a look at this example for more info (there is real drawings implementation):

https://github.com/Mikhus/canvas-gauges/blob/v2.1.3/examples/custom-drawings.html

Of course it means you'll need a bit deeper gauge implementation understanding. For that take a look at the source code itself. it should be pretty clear to read and understand, I hope.

All kind regards,
Mike
