### ISSUE TITLE
Use canvas-gauges with electron

### ISSUE THREAD

**Issue by LazeBear** [Mikhus/canvas-gauges#122]
As I'm pretty new to js and electron, this might be a stupid question, but I really can't find the way to solve it and here is the issue:
In the guidance, there are two ways to insert canvas gauge, the HTML way works fine for me. However, I'm struggling on the js way. when I paste the code into the js file, I got an error saying "LinearGauge is undefined".
Just wondering, in what way should I include or import canvas-gauge. 
I tried, var canvas = require("canvas-gauge") but don't know how to link the canvas with the LinearGauge method.
I also tried, put the code into the HTML file inside <script> tag, that doesn't work as well. 
Thanks for any help!

**Comment by LazeBear** [comment]
Also, with HTML, how to updating the value like gauge.value("10") as in js.
I used JQuery to change the 'data-value' attribute, but there is no animation at all.

**Comment by Mikhus** [comment]
gauge.value is not a function but setter. so correct way is
gauge.value = 10;

Could you, please, attach an example, where changing data-value attribute does not work, because I can't see any problem with that.

Thank you in advance!

**Comment by Mikhus** [comment]
Ah, yes, got some example where problems with animation on value change exists. So it's a bug...

**Comment by Mikhus** [comment]
Animation problem when updating through HTML-attribute is fixed in version 2.1.3
