### ISSUE TITLE
How to update data-value in real time

### ISSUE THREAD

**Issue by mivilleb** [Mikhus/canvas-gauges#127]
Sorry, a real noob here. It is not clear to me how to update the data value on a gauge at an interval, say every minutes from data obtained via a PHP request for example (ajax style).

From what I can see, the first time the HTML page is loaded and Gauge drawn, it uses the data-value attribute to draw the "needle" at the requested position. In my case I have wind direction changing every minute obtained from a weather station and what the new direction shown on the dial without having to reload the HTML page.

Is there a way to do this with canvas-gauges?

**Comment by Mikhus** [comment]
Sure you can, actually that is this component was created for.
As you said you can obtain new value to display on the gauge using ajax request or websockets, whatever technique you're going to use and then simply update this value on the gauge using: HTML API (by changing an attribute) or using JS API (it is much preferred way as you do not need to change DOM).

Example: 
Imaging you have a gauge on your page:

~~~html
<canvas type="radial-gauge" id="wind-gauge"></canvas>
~~~

and making requests using jQuery:

~~~javascript
// JS API way:
$.ajax("/get-wind-value.php").done(function(value) {
   document.gauges.get('wind-gauge').value = value;
});

// or HTML API way
$.ajax("/get-wind-value.php").done(function(value) {
   document.getElementById('wind-gauge').setAttribute("data-value", value);
});
~~~

**Comment by mivilleb** [comment]
Thank you, it works, this is what I have done:

`<canvas id="wind-gauge" data-type="radial-gauge"
        data-width="300"
        data-height="300"
        data-min-value="0"
        data-max-value="360"
        data-major-ticks="N,NE,E,SE,S,SW,W,NW,N"
        data-minor-ticks="22"
        data-ticks-angle="360"
        data-start-angle="180"
        data-stroke-ticks="false"
        data-highlights="false"
        data-color-="#222"
        data-color-plate="#222"
        data-color-major-ticks="#f5f5f5"
        data-color-minor-ticks="#ddd"
        data-value-box="true"
        data-value-text-shadow="false"
        data-color-circle-inner="#fff"
        data-color-numbers="#eee"
        data-borders="true"
        data-border-inner-width="0"
        data-border-middle-width="0"
        data-border-outer-width="10"
        data-color-border-outer="#ccc"
        data-color-border-outer-end="#ccc"
        data-border-shadow-width="0"
        data-font-value="Led"
></canvas>
<script>

var update = function() {
    $.getJSON("get-wind-value.php").done(function(data) {
       document.getElementById('wind-gauge').setAttribute("data-value", data.wind_dir);
       document.getElementById('wind-gauge').setAttribute("data-value-text", data.wind_speed);
    });
};

update();

var refInterval = window.setInterval('update()', 1000);

</script>`
