### ISSUE TITLE
when I use react-router Link to canvas-gauge`s page,but the canvas doesn`t render.

### ISSUE THREAD

**Issue by yourenA** [Mikhus/canvas-gauges#130]
Hello!
there was a problem when I user react-router Link to the page that I user canvas-gauges draw the canvas.
when I into the page the there is not any canvas on the page  , but if I press F5 to refresh the page ,the canvas is show . And my canvas-gauges version is 2.1.4.
Could you give me some suggestions ? thans~

my code
`
import  'canvas-gauges';
......
<canvas
                    data-type="linear-gauge"
                        data-width="160"
                        data-height="600"
                        data-border-radius="20"
                        data-borders="1"
                        data-bar-stroke-width="50"
                        data-minor-ticks="50"
                        data-min-value="-50"
                        data-max-value="150"
                        data-major-ticks="-50,-40,-30,-20,-10,0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150"
                        data-value={temperature}
                        data-units="°C"
                        data-color-value-box-shadow="false"
                        data-animation-duration="100"
                ></canvas>`

**Comment by Mikhus** [comment]
Can't reproduce this problem.

Using create-react-app and then simply editing src/App.js putting the code you provided works well as expected.

Can you provide more details?

**Comment by Mikhus** [comment]
No response, seems not actual...
