### ISSUE TITLE
Logarithmic scales

### ISSUE THREAD

**Issue by ptorrent** [Mikhus/canvas-gauges#131]
Hi,

At first, thanks for your work !

Is it possible to do Logarithmic scales ? 

![capture](https://cloud.githubusercontent.com/assets/6083644/24902066/50c21c34-1ea9-11e7-8e38-c2a1a3bd5222.PNG)

Thanks for your answer !

**Comment by Mikhus** [comment]
No, currently there is no such feature.

**Comment by ruudboon** [comment]
Would be awesome if this could be added
