### ISSUE TITLE
React Component for canvas-gauges

### ISSUE THREAD

**Issue by 1995parham** [Mikhus/canvas-gauges#138]
First of all thanks for your great library, I created react component for canvas-gauges [here](https://github.com/1995parham/react-canvas-gauges). I hope it help.

**Comment by Mikhus** [comment]
Great news! Thank you for your contribution, I will add the link to main README

**Comment by Mikhus** [comment]
Added

**Comment by 1995parham** [comment]
Thank you very much 👍
