### ISSUE TITLE
Digital gauge

### ISSUE THREAD

**Issue by Alpha0x** [Mikhus/canvas-gauges#139]
Hi,

Is it possible to draw only a box value with a title ? In order to display a digital gauge ?

Thank you

**Comment by Mikhus** [comment]
Sounds a bit strange as for me. If you want to display only numbers in some box, why to use a component with canvas drawings... It like shoot a bird with cannon...

**Comment by Alpha0x** [comment]
Thanks for your answer,
I know it's strange... I was just wondering if it is possible. In order to create Linear, Radial or Digital gauges with the same API and same functions
