### ISSUE TITLE
Change the format on ValueBox

### ISSUE THREAD

**Issue by ahanjrah** [Mikhus/canvas-gauges#142]
Hi,
Is there a way we can change the format of valueBox? For example, right now what I have is XXX.XX but when the number hits 200000, the valueBox shows it as: 200000.00.

Is there a way we can change this format to add commas and get rid of those decimal numbers? Precisely what I want to do is this: 200,000 or 10,000

Thanks.

**Comment by whurlston-cl** [comment]
use "valueText: v..toLocaleString()"

**var v = 100;**

var gauge = new RadialGauge({
    **value: v,
    valueText: (v*1000).toLocaleString(),**
    renderTo: 'right',
    borderShadowWidth: 0,
    animationDuration: 1500,
    animationRule: "linear",
    highlights: [
        {
            "from": 160,
            "to": 220,
            "color": "rgba(200, 50, 50, .75)"
        }
    ],
    units: "Km/h x1,000",
    majorTicks: [
        "0",
        "20",
        "40",
        "60",
        "80",
        "100",
        "120",
        "140",
        "160",
        "180",
        "200",
        "220"
    ],
    maxValue: 220,
    minValue: 0,
    minorTicks: 2,
    borders: false,
    height: 300,
    width: 300,
    strokeTicks: true,
    needleWidth: 2,
    needleType: "arrow",
    needleCircleOuter: true,
    needleCircleSize: 7,
    colorPlate: "#fff",
    needleCircleInner: false
}).draw();

**Comment by nbulaj** [comment]
Hi @Mikhus. I have the same question, but I need to output not only the value, but some additional info (for example units), that I don't want to show in default "units" bar. Is it possible ? I couldn't found this option in the docs.

**Comment by Rykad** [comment]
The documentation talks about attribute data-value-format for this purpose, but it didn´t work for me.
https://github.com/Mikhus/canvas-gauges/wiki/Gauge-HTML-API

However I found that these (undocumented) attributes will do part of the trick:
            valueDec: [number of decimal places]
            valueInt: [number of integer places]

Couldn´t find anything about adding commas.

Diego.

**Comment by Mikhus** [comment]
You can utilize valueText and draw any text you may want to...
