### ISSUE TITLE
Question: How to hand data over to gauge

### ISSUE THREAD

**Issue by bospre** [Mikhus/canvas-gauges#145]
Hello
this is not an issue, but a question, because I do not understand how to pass data to the gauges.
I have been using V1.x for a couple of gauges without problems.
I use arduinos for delivering data.
In the old version I used
 data-onready="setInterval( function() { Gauge.Collection.get('an_gauge_1').setValue(data_val);}, 200);"
in the configuration of each gauge

This is how my html page looks like (two gauges, one for wind speed, the other one for the direction)

<!DOCTYPE html>
<html>
    <head>
        <script src="http://172.16.0.29/arduino/gauge.min.js"></script>
        <title>Windgeschwindigkeit und -richtung</title>
        
     <script>
        var data_val1 = 0;
        var data_val2 = 0;
        var data_val3 = 0;
		

    function GetArduinoInputs()
		{
			nocache = "&nocache=" + Math.random() * 1000000;
			var request = new XMLHttpRequest();
			request.onreadystatechange = function()
			{
			if (this.readyState == 4) {
				if (this.status == 200) {
					if (this.responseXML != null) {
						document.getElementById("windgeschwindigkeit").innerHTML =
	this.responseXML.getElementsByTagName('windgeschwindigkeit')[0].childNodes[0].nodeValue;
				data_val1 = this.responseXML.getElementsByTagName('windgeschwindigkeit')[0].childNodes[0].nodeValue;
				document.getElementById("windrichtung").innerHTML =
				this.responseXML.getElementsByTagName('windrichtung')[0].childNodes[0].nodeValue;
				data_val2 = this.responseXML.getElementsByTagName('windrichtung')[0].childNodes[0].nodeValue;
				document.getElementById("datum_uhrzeit").innerHTML =
				this.responseXML.getElementsByTagName('datum_uhrzeit')[0].childNodes[0].nodeValue;
				data_val3 = this.responseXML.getElementsByTagName('datum_uhrzeit')[0].childNodes[0].nodeValue;
						}
					}
				}
			}
			request.open("GET", "ajax_inputs" + nocache, true);
			request.send(null);
			setTimeout('GetArduinoInputs()', 400);
			
		}

// animage all gauges on a page
window.addEventListener('load', function() {
    document.gauges.forEach(function(gauge) {
        setInterval(function() { gauge.value = data_val1; }, 200);
    });
});
	</script>

    </head>
    <body onLoad="GetArduinoInputs()">

				<center>
        <h1 align="left">Windgeschwindigkeit und -richtung</h1>

        <div align="left">
          <table width="800" border="1">
            <tr>
              <th scope="col">&nbsp;</th>
              <th scope="col">&nbsp;</th>
            </tr>
            <tr>
              <th scope="row">

    <canvas id="w_geschwindigkeit" 
    renderTo="w_geschwindigkeit"
    canvas data-type="radial-gauge"
    data-width="300"
    data-height="300"
    data-units="Km/h"
    data-min-value="0"
    data-max-value="220"
    data-major-ticks="0,20,40,60,80,100,120,140,160,180,200,220"
    data-minor-ticks="2"
    data-stroke-ticks="true"
    data-highlights='[
        {"from": 160, "to": 220, "color": "rgba(200, 50, 50, .75)"}
    ]'
    data-color-plate="#fff"
    data-border-shadow-width="0"
    data-borders="false"
    data-needle-type="arrow"
    data-needle-width="2"
    data-needle-circle-size="7"
    data-needle-circle-outer="true"
    data-needle-circle-inner="false"
    data-animation-duration="1500"
    data-animation-rule="linear"
    data-value-int="3"
    data-value-dec="2"
    data-value="windgeschwindigkeit"
    >
    </canvas></th>

              <td>
    <canvas id="an_gauge_2"
    renderTo="an_gauge_2"
    canvas data-type="radial-gauge"
    data-min-value="0"
    data-max-value="360"
    data-major-ticks="N,NE,E,SE,S,SW,W,NW,N"
    data-minor-ticks="22"
    data-ticks-angle="360"
    data-start-angle="180"
    data-stroke-ticks="false"
    data-highlights="false"
    data-color-plate="#222"
    data-color-major-ticks="#f5f5f5"
    data-color-minor-ticks="#ddd"
    data-color-numbers="#ccc"
    data-color-needle="rgba(240, 128, 128, 1)"
    data-color-needle-end="rgba(255, 160, 122, .9)"
    data-value-box="false"
    data-value-text-shadow="false"
    data-color-circle-inner="#fff"
    data-color-needle-circle-outer="#ccc"
    data-needle-circle-size="15"
    data-needle-circle-outer="false"
    data-animation-rule="linear"
    data-needle-type="line"
    data-needle-start="75"
    data-needle-end="99"
    data-needle-width="3"
    data-borders="true"
    data-border-inner-width="0"
    data-border-middle-width="0"
    data-border-outer-width="10"
    data-color-border-outer="#ccc"
    data-color-border-outer-end="#ccc"
    data-color-needle-shadow-down="#222"
    data-border-shadow-width="0"
    data-animation-duration="1500"
    data-value="55"
   >
    </canvas></th>

	              </td>
            </tr>
            <tr>
              <th scope="row">&nbsp;</th>
              <td>&nbsp;</td>
            </tr>
          </table>
        </div>

 			</center>
      <p align="center">Stand: <span id="datum_uhrzeit">...</span></p>      
      
Windrichtung:      <span id="windrichtung">...</span></p>      
Windgeschwindigkeit:      <span id="windgeschwindigkeit">...</span></p>      
      

</body>
</html>

I understand that this lines (below) are responsible for passing data to the gauges.
And I understand that document.gauges.forEach() adresses all gauges
// animage all gauges on a page
window.addEventListener('load', function() {
    document.gauges.forEach(function(gauge) {
        setInterval(function() { gauge.value = data_val1; }, 200);
    });

But how can I pass data_val1 to the gauge w_geschwindigkeit
and data_val2 to gauge an_gauge_2??
I looked in every example, but did not find a hint.
I found two issues with a similar topic, but the solution pointed out there, did not help me.

Maybe someone can enligthen me?
And maybe this can be added to the documentation?
Sincerely
Boris

**Comment by whurlston-cl** [comment]
replace "gauge.value = data_val1;" in your setInterval() with the following:

switch (guage.options.renderTo){
case "w_geschwindigkeit":
gauge.value = data_val1;
break;
case "an_gauge_2":
gauge.value = data_val2;
break;
}

**Comment by bospre** [comment]
Hello,
thank you for your response.

I tried your suggestion, but it does not work.
The gauges do not show the values.
There was a little typo, which I corrected (guage.options =>gauge.options).
I set one gaugevalue to a fixed value (gauge.value = "111";) for testing.

My page looks like this now (below), maybe you can have a look, because I do not see any mistake or reason, why this won't work:

Thank you in advance
Boris

<!DOCTYPE html>
<html>
    <head>
        <script src="http://172.16.0.29/arduino/gauge.min.js"></script>
        <title>Windgeschwindigkeit und -richtung</title>
        <script>

        var data_val1 = 0;
        var data_val2 = 0;
        var data_val3 = 0;
		

        function GetArduinoInputs()
		{
			nocache = "&nocache=" + Math.random() * 1000000;
			var request = new XMLHttpRequest();
			request.onreadystatechange = function()
			{
				if (this.readyState == 4) {
					if (this.status == 200) {
						if (this.responseXML != null) {
							document.getElementById("windgeschwindigkeit").innerHTML =
							this.responseXML.getElementsByTagName('windgeschwindigkeit')[0].childNodes[0].nodeValue;
							data_val1 = this.responseXML.getElementsByTagName('windgeschwindigkeit')[0].childNodes[0].nodeValue;
								
							document.getElementById("windrichtung").innerHTML =
							this.responseXML.getElementsByTagName('windrichtung')[0].childNodes[0].nodeValue;
							data_val2 = this.responseXML.getElementsByTagName('windrichtung')[0].childNodes[0].nodeValue;

							document.getElementById("datum_uhrzeit").innerHTML =
							this.responseXML.getElementsByTagName('datum_uhrzeit')[0].childNodes[0].nodeValue;
							data_val3 = this.responseXML.getElementsByTagName('datum_uhrzeit')[0].childNodes[0].nodeValue;
						}
					}
				}
			}
			request.open("GET", "ajax_inputs" + nocache, true);
			request.send(null);
			setTimeout('GetArduinoInputs()', 400);
			
		}

// animate all gauges on a page
window.addEventListener('load', function()
 {
    document.gauges.forEach(function(gauge) 
      {
        setInterval(function()
         { 
         switch (gauge.options.renderTo)
           {
		case "w_geschwindigkeit":
		gauge.value = "111";
		break;

		case "an_gauge_2":
		gauge.value = data_val2;
		break;
	   }
         }, 200);
      });
 });
 
  </script>
    </head>
    
    <body onLoad="GetArduinoInputs()">



				<center>
        <h1 align="left">Windgeschwindigkeit und -richtung</h1>


        <div align="left">
          <table width="800" border="1">
            <tr>
              <th scope="col">&nbsp;</th>
              <th scope="col">&nbsp;</th>
            </tr>
            <tr>
              <th scope="row">
              

   <canvas id="w_geschwindigkeit" 
    renderTo="w_geschwindigkeit"
    canvas data-type="radial-gauge"
    data-width="300"
    data-height="300"
    data-units="Km/h"
    data-min-value="0"
    data-max-value="220"
    data-major-ticks="0,20,40,60,80,100,120,140,160,180,200,220"
    data-minor-ticks="2"
    data-stroke-ticks="true"
    data-highlights='[
        {"from": 160, "to": 220, "color": "rgba(200, 50, 50, .75)"}
    ]'
    data-color-plate="#fff"
    data-border-shadow-width="0"
    data-borders="false"
    data-needle-type="arrow"
    data-needle-width="2"
    data-needle-circle-size="7"
    data-needle-circle-outer="true"
    data-needle-circle-inner="false"
    data-animation-duration="1500"
    data-animation-rule="linear"
    data-value-int="3"
    data-value-dec="2"
    
    >
    </canvas></th>

              
              
              
          
              
              <td>
   <canvas id="an_gauge_2"
    renderTo="an_gauge_2"
    canvas data-type="radial-gauge"
    data-min-value="0"
    data-max-value="360"
    data-major-ticks="N,NE,E,SE,S,SW,W,NW,N"
    data-minor-ticks="22"
    data-ticks-angle="360"
    data-start-angle="180"
    data-stroke-ticks="false"
    data-highlights="false"
    data-color-plate="#222"
    data-color-major-ticks="#f5f5f5"
    data-color-minor-ticks="#ddd"
    data-color-numbers="#ccc"
    data-color-needle="rgba(240, 128, 128, 1)"
    data-color-needle-end="rgba(255, 160, 122, .9)"
    data-value-box="false"
    data-value-text-shadow="false"
    data-color-circle-inner="#fff"
    data-color-needle-circle-outer="#ccc"
    data-needle-circle-size="15"
    data-needle-circle-outer="false"
    data-animation-rule="linear"
    data-needle-type="line"
    data-needle-start="75"
    data-needle-end="99"
    data-needle-width="3"
    data-borders="true"
    data-border-inner-width="0"
    data-border-middle-width="0"
    data-border-outer-width="10"
    data-color-border-outer="#ccc"
    data-color-border-outer-end="#ccc"
    data-color-needle-shadow-down="#222"
    data-border-shadow-width="0"
    data-animation-duration="1500"

   >
    </canvas></th>

	              </td>
            </tr>
            <tr>
              <th scope="row">&nbsp;</th>
              <td>&nbsp;</td>
            </tr>
          </table>
        </div>

 			</center>
      <p align="center">Stand: <span id="datum_uhrzeit">...</span></p>      
      
Windrichtung:      <span id="windrichtung">...</span></p>      
Windgeschwindigkeit:      <span id="windgeschwindigkeit">...</span></p>      
      


</body>
</html>

**Comment by bospre** [comment]
Me again....

This code works (both gauges are animeted with value stored in data_val2)

// animage all gauges on a page
window.addEventListener('load', function() 
   {
    document.gauges.forEach(function(gauge) 
     {
        setInterval(function() { gauge.value = data_val2; }, 200);
    });
 });

// ---
And this does not work, both gauges stay at "0":

// animate all gauges on a page
window.addEventListener('load', function()
 {
    document.gauges.forEach(function(gauge) 
      {
        setInterval(function()
         { 
          switch (gauge.options.renderTo)
           {
		case "w_geschwindigkeit":
		gauge.value = "111";
		break;

		case "an_gauge_2":
		gauge.value = data_val2;
		break;
	   }
         }, 200);
      });
 });

Thank you in advance for helping.
Sincerely
Boris

**Comment by whurlston-cl** [comment]
Since you are creating the gauge in HTML and not javascript, use renderTo.id:

switch ( gauge.options.renderTo.id ){
...
}

**Comment by bospre** [comment]
Thank you very much.
This solution now works.
I have to optimize my gauges now.
Boris
