### ISSUE TITLE
data-value-box in webview

### ISSUE THREAD

**Issue by iwanaditya** [Mikhus/canvas-gauges#149]
hi i trying to use examples in canvas-gauges using android webview but when i open it ,its not rendered.
the gauge is rendered ok but no tick needle.
when i set data-value-box to false the tick needle is rendered ok.
is there any solution to this because i realy need data-value-box ?

**Comment by karrarkazuya** [comment]
mobile webviews can not handle much html5. try to use less components and it'll work
