### ISSUE TITLE
Leading Zero Remove

### ISSUE THREAD

**Issue by epicycler** [Mikhus/canvas-gauges#151]
thanks for gauges, nice work

For my system I changed both instances of this line in function padValue in drawings.js
strVal[0] = '0' + strVal[0];
to
strVal[0] = ' ' + strVal[0];
so as to have leading space instead of leading zero in value display.
I hard coded instead of making it a parameter as I never use leading zeroes.
seems to work ok.

**Comment by caverna** [comment]
@epicycler, you don't need to do that...
just set de parameter "valueInt" to zero...
