### ISSUE TITLE
Request: Value in currency format, with commas and dollar sign

### ISSUE THREAD

**Issue by natecope** [Mikhus/canvas-gauges#159]
https://imgur.com/a/tkMY4

I'd like the value of the meter to allow for commas and dollar signs, to represent currency. Is this possible? Feature request maybe?

**Comment by Mikhus** [comment]
It is possible to utilize valueText option while updating gauge value to
set any text you want to have in value box, like:

document.gauges[0].update({ value: 15, valueText: "$15.00" })

Hope it helps.

All kind regards,
Mike

**Comment by natecope** [comment]
Works great! Thanks so much!
