### ISSUE TITLE
Not a issue but need some advice

### ISSUE THREAD

**Issue by Wargen1** [Mikhus/canvas-gauges#162]
Hi sorry for my simple question, i just want to read a value from a file on disk  and present it in a gauge every 5 sec, is there any body out there willing to share the code?

Im not a developer and have very little nolage about html and java

Thanks in advance /Wargen

**Comment by saiyanx** [comment]
Just a suggestion, but there are two ways you could do this using async calls or refreshing the whole page after every 5 sec so I would recommend using AJAX for async calls after every 5 sec, less resources plus faster

**Comment by Mikhus** [comment]
As suggested, you are making request and updating gauge value
