### ISSUE TITLE
Canvas gauge not refreshing

### ISSUE THREAD

**Issue by ChandTurakhia** [Mikhus/canvas-gauges#163]
Graph gets shown first time but later nothing shows up. I tried to add parameter     data-refresh="true"
which I know would not help but tried but to no use.

Graph turns up first time but not coming back to the same page. It vanishes. On Page reload it works.

Chandresh

       return (
            <div style = {{ marginLeft: '13%', marginTop:'2%' }}>
              <div className='svggauge'>
                <div onClick = {() => {this.props.getTeams()}} style={{ cursor: 'pointer' }}>
                .
<canvas data-type="radial-gauge"
    data-width="250"
    data-height="200"
    data-refresh="true"
    data-units="Percentage"
    data-min-value="0"
    data-value="75"
    data-value-box="false"
    data-max-value="100"
    data-major-ticks="0,20,40,60,80,100"
    data-minor-ticks="2"
    data-stroke-ticks="true"
    data-highlights='[
        {"from": 80, "to": 100, "color": "rgba(200, 50, 50, .75)"}
    ]'
    data-color-plate="#fff"
    data-border-shadow-width="0"
    data-borders="false"
    data-needle-type="arrow"
    data-needle-width="2"
    data-needle-circle-size="7"
    data-needle-circle-outer="true"
    data-needle-circle-inner="false"
    data-animation-duration="1500"
    data-animation-rule="linear"
></canvas>

                
                </div>
              </div>
            </div>
        );
    }
}

**Comment by Mikhus** [comment]
If you mean you need update the value, use a proper way to do that:
~~~javascript
gauge.value = myNewValue;
~~~

where new value you should obtain somewhere, for example using a specific request to your server, or from web socket, etc...
