### ISSUE TITLE
How to use variables

### ISSUE THREAD

**Issue by RitterD** [Mikhus/canvas-gauges#172]
Hi!

I'm trying to use variables to make the gauge more flexible. I receive some maximum values from my controller but when I pass them to the function the gauge looks like this:

![max_werte](https://user-images.githubusercontent.com/37876396/43254155-09cde09c-90c7-11e8-9c42-353f762c2cdc.jpeg)

As you can see in the top of the page: 6000 this is my max value. The digestion in other functions works but not in the one the gauge is drawn...

![max_werte_console](https://user-images.githubusercontent.com/37876396/43254341-7a6d6ee4-90c7-11e8-9e84-2432ab488b26.JPG)

Drehzahl means RPM... sorry
Here is my function:

`
function Drehzahl(val, max) {

    
    var max_val = parseInt(max);

    var steps = parseInt(max) / 10;

    var gauge_RPM = new RadialGauge({
        renderTo: 'canvas_rpm',
        width: 300,
        height: 300,
        units: "1/min",
        minValue: 0,
        maxValue: max,
        majorTicks: [
            "0",
            steps,
            steps * 2,
            steps * 3,
            steps * 4,
            steps * 5,
            steps * 6,
            steps * 7,
            steps * 8,
            steps * 9,
            steps * 10,

        ],
        minorTicks: 2,
        strokeTicks: true,
        highlights: [
            {
                "from": 5000,
                "to": max,
                "color": "rgba(200, 50, 50, .75)"
            }
        ],
        colorPlate: "#fff",
        borderShadowWidth: 0,
        borders: false,
        needleType: "arrow",
        needleWidth: 2,
        needleCircleSize: 7,
        needleCircleOuter: true,
        needleCircleInner: false,
        animationDuration: 1500,
        animationRule: "linear"
    }).draw();

    gauge_RPM.update({animation: false, value: val});

    console.log("Max_val: " + max);
    console.log("Steps: " + steps);
}
`
I realy want to use varibles can you please show me how?...

Thank you very much in advance!

**Comment by Mikhus** [comment]
The problem is that max is not defined

**Comment by RitterD** [comment]
Thank you very much @Mikhus for the quick response!

You mean like this?

`
function Drehzahl(val, max) {


    var max_val = parseInt(max);

    var steps = parseInt(max) / 10;

    var gauge_RPM = new RadialGauge({
        renderTo: 'canvas_rpm',
        width: 300,
        height: 300,
        units: "1/min",
        minValue: 0,
        maxValue: max_val,
        majorTicks: [
            "0",
            steps,
            steps * 2,
            steps * 3,
            steps * 4,
            steps * 5,
            steps * 6,
            steps * 7,
            steps * 8,
            steps * 9,
            steps * 10,

        ],
        minorTicks: 2,
        strokeTicks: true,
        highlights: [
            {
                "from": 6000,
                "to": max_val,
                "color": "rgba(200, 50, 50, .75)"
            }
        ],
        colorPlate: "#fff",
        borderShadowWidth: 0,
        borders: false,
        needleType: "arrow",
        needleWidth: 2,
        needleCircleSize: 7,
        needleCircleOuter: true,
        needleCircleInner: false,
        animationDuration: 1500,
        animationRule: "linear"
    }).draw();


    gauge_RPM.update({animation: false, value: val});

    console.log("Max_val: " + max_val);
    console.log("Steps: " + steps);
}
`
I geht NaN for both now...

![nan](https://user-images.githubusercontent.com/37876396/43255697-e1ed9d8e-90ca-11e8-80ee-c2307695a4dd.JPG)

**Comment by RitterD** [comment]
Okay, but look at this. I grab the maximum value with this function and I pass them to the Drehzahl function and the console gives me the correct value:

`function max_werte(result) {
    console.log("max_werte: "+result.status);
    console.log("***********************************MAX_VALUE_AUSLESEN***********************************");
    var hex = base64toHEX(result.value);
    console.log(hex);

    function split(hex){
        var commaSeperated = "";
        for(var i=0; i<=hex.length; i++){

            commaSeperated += hex.charAt(i);

            if(i==7 || i==15 || i==19 || i==21 || i==23 || i==25 || i==27){
                commaSeperated += ",";
            }
        }
        return commaSeperated.split(',');
    }
    var nutzwerte = [];
    nutzwerte = split(hex);
    //console.log(split(hex));
    console.log(nutzwerte);


    var RPM_max = "0x" + nutzwerte[0];
    var RPM_min = "0x" + nutzwerte[2];

    var temp_max= parseInt(nutzwerte[4],16);


    function swap32(RPM) {

        return ((RPM & 0xFF) << 24)
            | ((RPM & 0xFF00) << 8)
            | ((RPM >> 8) & 0xFF00)
            | ((RPM >> 24) & 0xFF);
    }

    console.log("RPM_max: "+swap32(RPM_max));
    console.log("RPM_min: "+swap32(RPM_min));
    console.log("Temp_max:" +temp_max);
    document.getElementById("crit_RPM").textContent = swap32(RPM_max);
    document.getElementById("crit_Temp").textContent = temp_max;
    var RPM_Max_var = parseInt(swap32(RPM_max));
    console.log("RPM_max_var: "+RPM_Max_var);
    Drehzahl([], RPM_Max_var);
}`

![klappt beim ersten mal](https://user-images.githubusercontent.com/37876396/43259873-140f4ff8-90d8-11e8-84ec-d42bfe05eb69.JPG)

Max_val and steps is shown correctly deliverd from the function Drehzahl:
function Drehzahl(val, max){
...
console.log("Max_val: " + max);
console.log("Steps: " + steps);
}
But then it turns into NaN. I dont get it....

**Comment by RitterD** [comment]
The problem is fixed. I forgot to set the max value in the subscription function, so they always receive no value.... fuck my life xD thank you very much!!!
