### ISSUE TITLE
In Half Radial Gauge, unwanted remaining gauge takes half height/width.

### ISSUE THREAD

**Issue by Rahulgarg30591** [Mikhus/canvas-gauges#174]
Hello @Mikhus, Thank you for such an amazing library. 

I am trying to consume the half radial gauge, using 
```
startAngle={90}
ticksAngle={180}
```

but the remaining gauge is taking unwanted height, is there a way I only render half gauge?

Thanks
Rahul Garg

**Comment by Mikhus** [comment]
there is no such option for the moment. BTW depending on your render you may hide half of the gauge by a wrapping div, positioning and overflow:hidden as an idea

**Comment by Rahulgarg30591** [comment]
Hello @Mikhus, rightly said and I have implemented in the same way you asked me to, but I am facing a new problem and that is with the value box, the value box is coming way below the gauge, is there a way by which offset can be added to the valueBox position to make it top, bottom, left or right?

**Comment by Mikhus** [comment]
Ca
