### ISSUE TITLE
Unable to update data in linear gauge

### ISSUE THREAD

**Issue by njeff3** [Mikhus/canvas-gauges#188]
I have been getting the following error when trying to use the gauge,update() function:
Uncaught TypeError: this.type.configure is not a function
    at o.value (gauge.min.js:26)
    at handleForm (<anonymous>:33:6)
    at <anonymous>:1:1

I have tried update is all the forms on the website examples, always getting this error. The value parameter as in gauge.value = 7.0 works file, but I'm unable to get the other data to update  and thus show on the screen. I am using v 2.1.15.

code examples:
gauge.update();
gauge.update( { "title": "New Title" } );
gauge.update( { title: "New Title" } );
and gauge.update with longer json strings.

Thanks

**Comment by vkuehn** [comment]
this is an old issue but no answer so far. So my two pence.
You could do
`var my_gauge = document.gauges.get('myGauge')
my_gauge.update({"title": "test"})`

if your gauge has id="myGauge"
