### ISSUE TITLE
Need some help React canvas-gauges for Animation

### ISSUE THREAD

**Issue by manivelgopi** [Mikhus/canvas-gauges#191]
Need some help React canvas-gauges for Animation duration. I have used animationDuration attribute but still the animation speed is very high.

could some one help how to change default value for animation Duration.

thanks in advance.

**Comment by efotin** [comment]
Try setting `animatedValue` property to `true`.

**Comment by OmarEnriqueGarciaTapia** [comment]
I have the same problem, it seems that the react library is neglected :S

**Comment by lhmoraes** [comment]
I have the same problem
