### ISSUE TITLE
180 Deg Tick

### ISSUE THREAD

**Issue by vtrufus** [Mikhus/canvas-gauges#194]
I am using data-ticks-angle="180" &  data-start-angle="90" to give me a horizontal gauge.  I have everything looking great, but my data-value box is way down at the bottom of the canvas.  Is there a way to make the canvas match the horizontal rectangle and move the data box up?

<canvas 
                data-width="300"
                data-height="300"
                data-type="radial-gauge" 
                data-value="0"
                data-min-value="0"
                data-max-value="100"
                data-ticks-angle="180"
                data-start-angle="90"
                data-major-ticks="0,20,40,60,80,100"
                data-minor-ticks="2"
                data-color-major-ticks="rgb(9,66,142)"
                data-color-minor-ticks="rgb(9,66,142)"
                data-stroke-ticks="false"
                data-bar-width="10" 
                data-bar-shadow="0" 
                data-color-bar-progress="rgba(41,171,226,1)" 
                data-color-bar="#fff"
                data-color-units= "rgb(9,66,142)"
                data-color-numbers="rgb(9,66,142)"
                data-borders="false"
                data-border-shadow-width="0" 
                data-border-inner-width="0" 
                data-border-outer-width="0" 
                data-border-middle-width="0" 
                data-highlights="false" 
                data-value-box-stroke="0" 
                data-color-value-box-shadow="0" 
                data-color-value-text= "rgb(9,66,142)"
                data-value-box-border-radius="0"
                data-value-text-shadow="0" 
                data-color-value-box-background="transparent"
                data-value-Dec= "false"
                data-value-Int= "0" 
                data-needle="false"
                data-animation-rule="linear"
                data-animation-duration="150">
                
        </canvas>
![gauge](https://user-images.githubusercontent.com/42280034/64202426-19b4b900-ce5f-11e9-996d-5eb04a17ce41.JPG)

**Comment by Mikhus** [comment]
Hi. Wrap canvas into div. Give that div a height of 1/2 height of canvas
and overflow:hidden.

вт, 3 вер. 2019, 22:25 користувач vtrufus <notifications@github.com> пише:

**Comment by vtrufus** [comment]
Thanks for the help.
