### ISSUE TITLE
hide complete gauge

### ISSUE THREAD

**Issue by vkuehn** [Mikhus/canvas-gauges#198]
document.gauges.get('myGauge').display = "none";
does not do anything, how would I correctly toggle showing/Hide for a complete gauge ?

BTW
Thanks for the library !

**Comment by Mikhus** [comment]
Gauge obtained by this way is not a DOM element, but corresponding Gauge object implementation.
You need to set visibility option on a DOM element instead, which can be done in any way you prefer:

```
// vanilla js
document.getElementById('myGauge').style.display = 'node';
// any other using majority of tools and frameworks
```
