### ISSUE TITLE
feature: Gradient for gauge

### ISSUE THREAD

**Issue by pke** [Mikhus/canvas-gauges#199]
Is there currently a way to use a gradient (blue to red) for the (linear) gauges?

**Comment by vkuehn** [comment]
check out the documentation
https://canvas-gauges.com/documentation/user-guide/configuration
Color Options
..
 Each color configuration is usually a string value representing the color in one of HEX (#000000-#FFFFFF), RGB (rgb(0, 0, 0)-rgb(255,255,255)) or RGBA (rgba(0,0,0,0)-rgba(255,255,255,1)) formats. Some elements supports gradients. In this case the color of an element could be configured as color start and color end parts.
...
ok ?
