### ISSUE TITLE
bug: Fast value updates stale value box

### ISSUE THREAD

**Issue by pke** [Mikhus/canvas-gauges#201]
Fast (0.5s) successive updates to `data-value` will update the gauge but not the value box. If the updates stop, the gauge will drop down to the value in the value box, not stay at the value of `data-value`.

```js
function TempGauge(props) {
      return (
        html`<canvas 
        data-type="linear-gauge"
        data-width="120"
        data-height="400"
        data-borders="0"
        data-bar-stroke-width="20"
        data-minor-ticks="10"
        data-major-ticks="0,10,20,30,40,50,60,70,80,90,100"
        data-value=${props.temp}
        data-units="°C/F"
        data-color-value-box-shadow="true"
        ></canvas>`
      )
    }
```

**Comment by ManniAT** [comment]
The gauge fails to update if the new value is set while the animation is in progress. (Needle jumps back).
I had a problem that the gauge missed updates - then I set animation duration to 50 (500 is default) and it worked with my update frequency.

**Comment by pke** [comment]
Thanks for the tip, I will try it out.
