### ISSUE TITLE
Is Tick Length Variable?

### ISSUE THREAD

**Issue by tomherold** [Mikhus/canvas-gauges#204]
I looked at all the configuration options, but could not find a parameter that defines the length of the major tick marks. See my attached graphic where I wanted the grey ticks shorter.

<img width="296" alt="test" src="https://user-images.githubusercontent.com/2873316/71321734-3d5b4800-24be-11ea-9338-62bcbf122671.png">

**Comment by lminggang** [comment]
Have you solved the problem? I would also like to try to make the scale smaller

**Comment by Mikhus** [comment]
Yes, it refer to "Fonts Customization Options" of the documentation https://canvas-gauges.com/documentation/user-guide/configuration

**Comment by cypis007** [comment]
> Yes, it refer to "Fonts Customization Options" of the documentation https://canvas-gauges.com/documentation/user-guide/configuration
> 
> Hints:
> 
> * fontNumbers: specifies font family for the tick numbers.
> * fontNumbersSize: Size of the font for tick numbers in relative units.

But how to change Tick **length** and **width** on _Radial Gauge_? So far all Radial Charts are having Major Tick Length = 2 x Minor Tick Length.  How to define Major Tick length as 150% of Minor Tick length ?
I would like to have result same as on scale below:
- Thick like 0,1000,2000, etc,
- Thinner like 500,1500, etc
- Thin and short like 100, 200, 300
![3-121](https://user-images.githubusercontent.com/20145799/79360358-17adef00-7f44-11ea-9858-780bb2512605.jpg).

**Comment by katyshin** [comment]
The tick size parameters is very lacking to cover 90% of all tasks... And the arrangement of the text outside of gauge ( when data-numbers-marginis very negative value, the text by the margin is cut off).
