### ISSUE TITLE
Bug? - broken gauges 

### ISSUE THREAD

**Issue by JanusHL** [Mikhus/canvas-gauges#205]
Hi,
After a few minutes of render several gauges with Firefox, suddenly all the gauges become broken.
![gauges_broken](https://user-images.githubusercontent.com/40386599/71324907-385dbf00-24e5-11ea-9c60-559b81af2a20.JPG)

**Comment by Mikhus** [comment]
Information you provided is not enough to identify a problem...

**Comment by wonderbock** [comment]
Dear Mikhus, same occurs here.
I attach the webpage. (i just hacked the update function to provide dummy values)
Leonardo 
[broken_gauges.zip](https://github.com/Mikhus/canvas-gauges/files/5825675/broken_gauges.zip)

**Comment by github212** [comment]
hi Mikhus,
i have the same error in the visualisation from iobroker.

![grafik](https://user-images.githubusercontent.com/919503/187041752-e77d3d40-7c03-47bc-8317-3af099e6eefe.png)

i am using iobroker on an laptop with win11. the error occured under firefox 103.0.2 (64 bit) after a while (minute or so) without other acticity on the laptop.
i have already done:  clear cache, private tab.
The visualization under windows edge is OK.

Thomas
