### ISSUE TITLE
Compass 180 degrees off.

### ISSUE THREAD

**Issue by RegencySoftware** [Mikhus/canvas-gauges#46]
First let me say great work on this gauge. 

I was using your compass JavaScript example. In the code it has a random number set to demostrate the compass. 

For example: If you set the range between 84 and 94 (East) the compass points West.  It is 180 degrees off in all test cases.

**Comment by cmgreenman** [comment]
I'm implementing a compass as well.   Actually I'm making an apparent wind gauge for a sailboat.   You are correct that the compass is 180 off.   I believe it assumes a 0 value pointing straight down.   You can set the start angle to 180 and it will correct it.

**Comment by Mikhus** [comment]
Thanks for investigation. If someone can propose a PR to fix this I'll be very appreciated, because for the moment I'm busy with v2.0.0. Otherwise I will be able to fix it a bit later...

**Comment by Mikhus** [comment]
Actually that was only misconfiguration issue in example.
With v2.0.0 examples there is correct definition.

Main idea is to move startAngle to 180 degrees (which is on top of the gauge) and properly re-define major ticks names.

[Examples](https://canvas-gauges.com/documentation/examples/#radial-gauges-as-compass)
