### ISSUE TITLE
Can I hide specific majorTicks on a gauge, so that only a few are visible?

### ISSUE THREAD

**Issue by sotabound** [Mikhus/canvas-gauges#50]
I have a gauge that I am working on and my client wants to only show a few of the majorTicks on the gauge. I know that I will need entries x10 to 100 to make a gauge that functions appropriately. can I use something like a CSS call to hide the specific majorTick? ie. '10'{this.css('visibility, 'transparent')}? Any hint would be nice!

**Comment by Mikhus** [comment]
Hi. Gauge is drown on a canvas, so it's a bitmap and does not have any relation to CSS. As a result there is no way to hide specific ticks unless changing drawing algorithm itself. So within core implementation it is currently not possible.

**Comment by sotabound** [comment]
Hi Mikhus, thanks for the reply. I probably used CSS when I did not need to. I looked more deeply in your code and I found that the config changes all of the Major ticks and not just one. I understand that it would be difficult to extend the config on the "strokeStyle" of the majorTicks (ctx.strokeStyle = config.colors.majorTicks;). What if I wanted to do something like the following:
majorTicks: [{tick:'0', color:'#000000'}, '10', '20', '30', '40', '50', '60', '70', '80', '90', '100'], 

Could I extend your library to change the configuration? I would prefer not to change the code in gauge.js, however maybe I could create a "plugin" of sorts that could extend it and apply what I am describing?

I think you have done an excellent job of making these gauges possible using html5 canvas! Very very cool stuff, keep up the great work!

**Comment by Mikhus** [comment]
It is opensource under MIT license, so, please, feel free to do any modifications. There is no limits, so you can fork, modify and pull your changes. All that is highly appreciated!

**Comment by Mikhus** [comment]
This feature will be added in upcoming release 2.0.4. It will be possible to specify specific colors for major ticks and tick numbers separately as arrays of colors instead of a single color value. For example:

```html
<canvas data-type="radial-gauge"
               data-major-ticks="0,50,100,150,200"
               data-color-numbers="transparent,red,green,blue,black"
               data-color-major-ticks="black,red,green,blue,black"
></canvas>
```
