### ISSUE TITLE
V2.xx doesn't work very well for me ...

### ISSUE THREAD

**Issue by softfoot** [Mikhus/canvas-gauges#53]
I just had a try at upgrading from 1.0.5 to 2.x.x and found that none of the examples in 2.10, 2.0.1 and "master" (I assume this is the "trunk") do not work for me.

Either they don't display a gauge at all or the needle is missing (or disappears after a second or so)

This was under "Pale Moon" v26.4.0

Under Firefox 47.0.1 it seemed better in that "scripted.html" and "linear-component.html" seemed to work OK but "radial-component.html" and "radial.html" didn't display any guages.

Is 2.x.x a release?? or is it "work in progress"??

1.0.5 works fine :-)

TIA
Dave

**Comment by Mikhus** [comment]
Have you read release notes?
https://canvas-gauges.com/releases/2.0.0/

"This release contains breaking changes in comparison to version 1.x.x. Old end-user code will not work with gauges from this release properly, so, please, before updating gauges code to version 2 make sure you read this list of changes and all referring information."

**Comment by Mikhus** [comment]
Checked under firefox specified example, There was a problem with custom webfont loading, not with gauges themselves. In FF FontFace.family will contain quote marks, so it's better to do a match(/foontName/) instead of making a strict check === 'familyName'.

This will be updated in docs and in examples in upcoming v2.0.1

**Comment by dec** [comment]
Hello,

I also note the problem with the font here, but, the samples works as expected to me.

**Comment by Mikhus** [comment]
v2.0.1 will be published in a minutes, there should be fixed those problems

**Comment by Mikhus** [comment]
version 2.0.1 is published, problem with font have to be fixed in examples

**Comment by softfoot** [comment]
OK I just tried the latest "trunk" and the problems I was having seem now to be fixed :-)

In an earlier response you said " read this list of changes" but I couldn't find such a document.

Is there a document that indicates changes in the interface ???

One obvious example is that it looks as though the "v1.x.x" property
    data-value-format=2.1
is now replaced by 
    data-value-int="2"
    data-value-dec="1"

Best regards,
Dave

**Comment by Mikhus** [comment]
@softfoot Meanwhile, I added [migration guide](https://canvas-gauges.com/migration/), which I hope will be helpful if you still have any needs on this :)

**Comment by softfoot** [comment]
Excellent :-)
It will be very useful.
Dave
