### ISSUE TITLE
Needle spins crazy on first change

### ISSUE THREAD

**Issue by stefanpoensgen** [Mikhus/canvas-gauges#63]
I update the value with onclick="gaugePS.value=200", onclick="gaugePS.value=250" etc.

On first click the value goes like 541245 and after animation to 200
On second click everthing is ok

**Comment by Mikhus** [comment]
Could you, please, provide more detailed piece of code to make me able to reproduce this behavior?

**Comment by stefanpoensgen** [comment]
`<script>
	var gaugePS = new RadialGauge({
		renderTo: 'gauge-ps',
		width: 400,
		height: 400,
		units: 'PS',
		minValue: 0,
		maxValue: 1000,
		majorTicks: ['0', '100', '200', '300', '400', '500', '600', '700', '800', '900', '1000'],
		minorTicks: 2,
		ticksAngle: 270,
		startAngle: 45,
		strokeTicks: true,
		highlights  : [
			{ from : 457,  to : 880, color : 'rgba(78,   78, 76, 0.5)' },
			{ from : 880, to : 1000, color : 'rgba(225, 7, 23, 0.75)' }
		],
		valueInt: 1,
		valueDec: 0,
		colorPlate: "#fff",
		colorMajorTicks: "#686868",
		colorMinorTicks: "#686868",
		colorTitle: "#000",
		colorUnits: "#000",
		colorNumbers: "#686868",
		valueBox: true,
		colorValueText: "#000",
		colorValueBoxRect: "#fff",
		colorValueBoxRectEnd: "#fff",
		colorValueBoxBackground: "#fff",
		colorValueBoxShadow: false,
		colorValueTextShadow: false,
		colorNeedleShadowUp: true,
		colorNeedleShadowDown: false,
		colorNeedle: "rgba(200, 50, 50, .75)",
		colorNeedleEnd: "rgba(200, 50, 50, .75)",
		colorNeedleCircleOuter: "rgba(200, 200, 200, 1)",
		colorNeedleCircleOuterEnd: "rgba(200, 200, 200, 1)",
		borderShadowWidth: 0,
		borders: true,
		borderInnerWidth: 0,
		borderMiddleWidth: 0,
		borderOuterWidth: 5,
		colorBorderOuter: "#fafafa",
		colorBorderOuterEnd: "#cdcdcd",
		needleType: "arrow",
		needleWidth: 2,
		needleCircleSize: 7,
		needleCircleOuter: true,
		needleCircleInner: false,
		animationDuration: 1500,
		animationRule: "dequint",
		fontNumbers: "Verdana",
		fontTitle: "Verdana",
		fontUnits: "Verdana",
		fontValue: "Led",
		fontNumbersSize: 20,
		fontTitleSize: 24,
		fontUnitsSize: 22,
		fontValueSize: 50,
		animatedValue: true
	});
	gaugePS.draw();
	gaugePS.value = "510";

</script>

<a href="#" onclick="gaugePS.value=570">570</a>
<a href="#" onclick="gaugePS.value=583">583</a>
<a href="#" onclick="gaugePS.value=830">830</a>
<canvas id="gauge-ps"></canvas>`

**Comment by Mikhus** [comment]
Thank you for contribution!
Yes, there is a problem with this example. I will add some additional dumb checks which would prevent of these kind of problems in the next release. BTW, you can fix this issue on your side simply changing the type of the initial value you assign to the gauge by modifying this line:

```javascript
gaugePS.value = "510";
```

to this one:

```javascript
gaugePS.value = 510;
```

Hope it helps!

**Comment by stefanpoensgen** [comment]
ok that was to easy :)
you can see my working example on my demo page http://new.mcchip-dkr.com/chiptuning-fahrzeug-datenbank

You need to select a car in the selects. 

PKW -> Mercedes Benz ->C-Kl. (W204) -> 63 AMG 6.3 V8  457PS

Now you could see a button "Stufe 1", click on it an switch to "Stufe 2" or something else.

**Comment by Mikhus** [comment]
@stefanpoensgen, That looks really awesome! Are you satisfied with gauges?

**Comment by stefanpoensgen** [comment]
yes it's awesome. exactly what i need for my new website. and it runs so smooth even on mobile devices.
and i could export it to pdf thats really cool. [mercedes-benz-c-kl.-w204-63-amg-6.3-v8-stufe-6-mc830_print.pdf](https://github.com/Mikhus/canvas-gauges/files/495433/mercedes-benz-c-kl.-w204-63-amg-6.3-v8-stufe-6-mc830_print.pdf)

But i want to set font to italic mode and could not find how to archieve that

**Comment by Mikhus** [comment]
For the moment it is not that easy to achieve... The only possible way I could imagine is that you may use the font which has italic glyph, but it is too crappy.

I will add a bit more advanced font-styling features in the next release, so you would be able to do that.

**Comment by stefanpoensgen** [comment]
That would be nice :+1:

**Comment by Mikhus** [comment]
@stefanpoensgen Release 2.0.6 is published moments ago. You can now configure font-style and font-width on gauge text elements. More info in [docs](https://canvas-gauges.com/documentation/user-guide/configuration#fonts-customization-options)

**Comment by Mikhus** [comment]
Fixed in release 2.0.6
