### ISSUE TITLE
License in minified file

### ISSUE THREAD

**Issue by yorl1n** [Mikhus/canvas-gauges#64]
Please add a license to the minified build. 

According to the license: 

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Accessible for the download compiled minified file doesn't contain this info.
Thanks in advance.

**Comment by Mikhus** [comment]
oops, thanks! Actually that was present in v1, but seems I missed this... Will be added in the next release

**Comment by Mikhus** [comment]
Fixed in release 2.0.6
