### ISSUE TITLE
MajorTicks Update

### ISSUE THREAD

**Issue by ihabadly** [Mikhus/canvas-gauges#66]
Thanks for your continuous effort and kind help. Kindly find the code I am trying, and it gives a problem with the majorTicks, after updating gauge to the latest, the behavior is different, no more sending error to console but still doesn't update correctly.

[cgng1.rar.zip](https://github.com/Mikhus/canvas-gauges/files/496133/cgng1.rar.zip)

**Comment by Mikhus** [comment]
Yeah! @ihabadly, thank you very-very much! That's really hidden weird bug here! And it's critical, so will update release as soon as possible.

**Comment by Mikhus** [comment]
Now it's fixed in release 2.0.7 and published.
Could you, please, confirm and close?

**Comment by ihabadly** [comment]
Thank You very much, it's working now.
