### ISSUE TITLE
Migration Documentation Issue

### ISSUE THREAD

**Issue by Khalinda** [Mikhus/canvas-gauges#68]
On page "https://canvas-gauges.com/migration/".  There are no "valueFormatInt" or "valueFormatDec" options...  instead they are "valueInt" and "valueDec".

**Comment by Mikhus** [comment]
@Khalinda, thank you for contribution!

Could you, please, confirm it is fixed now and close this issue?

**Comment by Khalinda** [comment]
Thank you, Mykhailo!
