### ISSUE TITLE
May be it will be interesting for you to test all parameters in GUI

### ISSUE THREAD

**Issue by GermanBluefox** [Mikhus/canvas-gauges#71]
I implemented here all 125 parameters and people can easily play with it:
http://iobroker.net:8082/vis/edit.html?CanvasGauges#Gauges
Or just static visualization:
https://iobroker.net:8080/vis/index.html?CanvasGauges#Gauges

![image](https://cloud.githubusercontent.com/assets/4582016/18921182/2425b238-85a4-11e6-97dc-11f8e50d33d9.png)

The translation will last a bit. But it will be definitely done.

**Comment by GermanBluefox** [comment]
Please close the issue, as you read it.

**Comment by Mikhus** [comment]
Wow!!!! That's amazing! Thank you!
 
I'd like to ask if there is a possibility with your tool to do something like this:
 - Select a single type of the gauge
 - Play with it's settings
 - Obtain HTML or JavaScript resulting code
 - without a need to design entire page
 - without saving anything on a server-side
 - integrate it into some other web-site (like, for example, we can inject plunker into some web-page)

I would really interested to have something like this on canvas-gauges.com

Even if there are no such options, I'd like to ask you for permission to refer your example from docs page on canvas-gauges.com Is it possible somehow?

**Comment by GermanBluefox** [comment]
Hello Mikhail,
I understand why you ask it. It is good idea for widget constructor.

But I must say, that no: you can't now extract html/js code.
But it should be not to hard to get such funktionality.
The interface is freely extendable and I can try to place the button
"extract the code" and build the code dynamically. It should be easy. Let
me try it.

And yes you can link the page.
Your library btw is the best non svg thing I have ever seen.

Greetings,
Bluefox

28 Сен 2016 г. 18:44 пользователь "Mykhailo Stadnyk" <
notifications@github.com> написал:
