### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ihabadly** [Mikhus/canvas-gauges#74]
Is it possible to add a feature making it possible to configure linear gauges as sliders?

Thanks.

**Comment by Mikhus** [comment]
What do you mean? Them are pretty configurable to make them look of different look & feel. [Examples](https://canvas-gauges.com/documentation/examples/#other-custom-linear-gauges) available.

**Comment by ihabadly** [comment]
For a slider, I need to be able to pull the slider (needle) and move it from place to another.
Is this possible, may be I am missing something in the examples.
