### ISSUE TITLE
If min is not 0 => wrong highlights 

### ISSUE THREAD

**Issue by GermanBluefox** [Mikhus/canvas-gauges#76]
![image](https://cloud.githubusercontent.com/assets/4582016/19168883/64c33de6-8c12-11e6-81ec-41d24f3ef985.png)

I can fix the issue when I subtract the minValue from highlights "from/to".

![image](https://cloud.githubusercontent.com/assets/4582016/19169042/eeee5992-8c12-11e6-9e00-416465a2a378.png)

**Comment by Mikhus** [comment]
Fixed in 2.1.0 branch
