### ISSUE TITLE
360 degree Radial Gauge - Value change long way around

### ISSUE THREAD

**Issue by storerjeremy** [Mikhus/canvas-gauges#77]
If you have a radial gauge with values between 0 and 360 like a compass, when you change the value from say 5 to 355 the needle animation takes the long way around the circle not the shortest distance. In certain situations like showing a heading it would make sense for the needle to take the shortest route to the new value.

Is there a config option to make the animation take the shortest distance around the circle?

Thanks,

**Comment by Mikhus** [comment]
not for the moment. I will add this feature in the next release

**Comment by storerjeremy** [comment]
Awesome, thanks.

**Comment by Mikhus** [comment]
Implemented in branch 2.1.0

**Comment by kenzotakane** [comment]
Hi Mikhus,

It is not working in ver. 2.1.5
Or... am I doing something wrong?

Help me... please

**Comment by kenzotakane** [comment]
Now it is OK.
I found a <canvas> option:  data-use-min-path="true"
