### ISSUE TITLE
needle animation problem with webpack (or rollup)

### ISSUE THREAD

**Issue by ericMartin386** [Mikhus/canvas-gauges#79]
Hi

I have a problem animating the gauge with web pack. In the animate function, when calculating the start time ns.Performance.now() returns a value that is way too big compared to the Date.now() and using that value makes the animation weird (the needle jumps from one value to another and sometime disappears completely). Patching the code to use window.performance.now() fix the problem... Is there something that I am missing?

**Comment by Mikhus** [comment]
It's related to more generic problem with loading CommonJS modules, which is described in issue #78

**Comment by socmag** [comment]
I'm having this problem as well :(

Other than this it's awesome.

**Comment by Mikhus** [comment]
Fixed in commit https://github.com/Mikhus/canvas-gauges/commit/ab1095188c6991a19e2d49cfab0c29b9824afcd1

Will be released in v2.1.0
