### ISSUE TITLE
radial gauge does not move on IOS

### ISSUE THREAD

**Issue by roscop13** [Mikhus/canvas-gauges#83]
Hello,
We are using your Gauge in an Ionic/Cordova project, the radial gauge works great in Android but not on IOS. See the IOS screenshot below, the needle is stuck vertically and does not move, anybody else experiencing the same issue?
![img_2872 1](https://cloud.githubusercontent.com/assets/16372890/19987655/9e07c1ec-a21c-11e6-8fa8-9acf7a3f74b3.jpg)

Thanks for your great work

**Comment by Mikhus** [comment]
I have tested with iPhone 6s+, iOS 10.1.1 both Safari (default) and Firefox browsers works pretty well as expected.

So please, provide more information about the environment on which you facing this issue:
- device type
- OS version
- Browser version

Thank you in advance.

**Comment by Mikhus** [comment]
Closing this issue as can not reproduce and there is no confirmations for a long time.
