### ISSUE TITLE
majorTicks do not work for numbers and decimals

### ISSUE THREAD

**Issue by leroygumede** [Mikhus/canvas-gauges#85]
If you set the majorTicks to the following values, gauge becomes inconsistent
This is for version 1
```
minValue: 0,
maxValue: 100,
majorTicks: [0, 1, 5, 10, 15, 20, 50, 75, 100],
```

**Comment by Mikhus** [comment]
Currently version 1 is out of my scope for support. So if someone still need this, feel free to propose a PR for this bug. In other case I can't promise it will be fixed soon.
