### ISSUE TITLE
If scan the DOM on ready

### ISSUE THREAD

**Issue by GermanBluefox** [Mikhus/canvas-gauges#87]
My editor has over 5000 elements on the page. And canvas-gauges scan at DOMready all these elements.

It would be very useful to make this feature controllable and create gauges only dynamically. 
5000 take about 1.5 seconds to be "checked".  

Just now I disabled this line:
https://github.com/Mikhus/canvas-gauges/blob/master/lib/DomObserver.js#L112
And everything is fast again.

**Comment by Mikhus** [comment]
I could propose to have some global flag to prevent auto DOM check. Will add this in 2.1

**Comment by Mikhus** [comment]
Implemented in 2.1 branch
