### ISSUE TITLE
Suggestions: Add additional padding to elements

### ISSUE THREAD

**Issue by RURon** [Mikhus/canvas-gauges#90]
Hello Mikhus, great piece of code, thank you!

I only miss one thing to make "my" gauge look perfect: Over here the numbers in the gauge are touching the main ticks. Unfortunately this is only with some of the ticks...maybe have a look at my screenshot - I'm using the default font. Especially the 11 and 13 look bad.

![14-12-_2016_17-41-49](https://cloud.githubusercontent.com/assets/17233445/21191241/c96fbf24-c224-11e6-83f3-c90d43fdaac4.png)

**Comment by Mikhus** [comment]
Could you please share your gauge config? That's interesting case I want to investigate it.

**Comment by RURon** [comment]
Sure! Heror you go:

`
<canvas  
        id="my-gauge-${uuid}"
        style="display: inline-block;"
        data-type="radial-gauge"
        data-width="250"
        data-height="250"
        data-units="Volt"
        data-title="false"
        data-value="${BalkonVCC.sensorVariable.value}"
        data-min-value="10"
        data-max-value="14"
        data-major-ticks="10,11,12,13,14"
        data-minor-ticks="10"
        data-stroke-ticks="true"
        data-highlights='[
            { "from": 10, "to": 11, "color": "rgba(255,0,0,1)" },
            { "from": 11, "to": 12, "color": "rgba(255,255,0,1)" },
            { "from": 12, "to": 13, "color": "rgba(0,255,0,1)" },
            { "from": 13, "to": 14, "color": "rgba(255,155,0,1)" }
        ]'

        data-color-plate="#fff"
        data-color-major-ticks="#000"
        data-color-minor-ticks="#000"
        data-color-title="#000"
        data-color-units="#000"
        data-color-numbers="#000"
        data-color-needle="rgba(255, 0,0, 1)"
data-needle-shadow="false"
data-needle-type="arrow"
data-color-needle-shadow-up="#f00"
data-color-needle-shadow-down="#999"
        data-value-box="true"
data-value-int="2"
data-value-dec="1"
        data-animation-rule="bounce"
        data-animation-duration="500"
        data-font-value="Led"
data-font-numbers-size="30"
data-font-numbers-weight="900"
data-font-units-weight="900"
        data-animated-value="true"
></canvas>`

**Comment by Mikhus** [comment]
Aha, I see. So the problem here when you increase numbers font size. Currently I can suggest you to decrease numbers font size from 30 to 25 or 20. In the next release I will add auto-detection of numbers position relatively to the font-size to fix this.

**Comment by RURon** [comment]
...great, thank you!

**Comment by RURon** [comment]
While at it, maybe a vertical adjustment option to move the unit label ("Volt" in my example) could be neat as well when playing around with different fonts and all that

**Comment by Mikhus** [comment]
Good suggestion, thank you. I'll see what can I do for the next release here.

**Comment by Mikhus** [comment]
Automatic font size detection on drawing is implemented in branch v2.1.1

**Comment by Mikhus** [comment]
Margins implemented in v2.1.1

**Comment by RURon** [comment]
beautiful!
