### ISSUE TITLE
Use window.devicePixelRatio

### ISSUE THREAD

**Issue by mainstreetmark** [Mikhus/canvas-gauges#91]
I seem to be doing a lot of:

    ...
	borderOuterWidth: 3 * window.devicePixelRatio,
	borderMiddleWidth: 5 * window.devicePixelRatio,
	borderInnerWidth: 3 * window.devicePixelRatio,
    ...

When I **don't** do that, I get different appearance between my retina Macbook Pro and my old mini.  Should widths be specified in "pixels" and canvas-gauges automatically apply the pixel ratio internally?

**Comment by Mikhus** [comment]
It ought to be like that, so it is simply a bug, thank you for contribution.

**Comment by Mikhus** [comment]
Fixed in branch v2.1.1
