### ISSUE TITLE
animated updates do not clear previous animations

### ISSUE THREAD

**Issue by mainstreetmark** [Mikhus/canvas-gauges#94]
if I perform an animated gauge update, and then later perform a faster animated update, the faster one completes, and then the needle finishes animating to the older value.  For example:

     gauge.value = 10
     gauge.update({animationDuration:10000});
     // wait 5 seconds
     gauge.value = 5
     gauge.update({animationDuration:2000})

After 10 seconds, the needle points to 10, when it should point to 5, with several conflicting needle states in between.

I suspect the previous animation should be cleared with each update, if it doesn't happen to be completed.

(the case i'm having is one of my values is polled, but every so often an event happens that requires a quick new reading, but the slower process animations are still running)

**Comment by Mikhus** [comment]
Fixed in branch v2.1.1
